### ISSUE TITLE
Midnight Commander integration

### ISSUE THREAD

**Issue by adimetrius** [Vostok-space/odcey#1]
Чтобы смотреть odc в Midnight Commander по F3, нужно настроить ~/.config/mc/mc.ext (или Ф9-Команда-Редактировать файл расширений):

#odc BlackBox Component Builder container document
shell/.odc
    View=%view{ascii} odcey text %f

Можно в README это указать.

**Comment by adimetrius** [comment]
Поскольку "_Это особенность snap. Он не даёт доступа к общему /tmp, и каждый snap-пакет использует собственный tmp. При обращении к таким файлам лучше использовать стандартный ввод odcey text < /tmp/0/Mod/Figures.odc_"

то в mc.ext команду такую:
#odc BlackBox Component Builder container document
shell/.odc
View=%view{ascii} odcey text **<** %f

**Comment by ComdivByZero** [comment]
Добавлено в README
