### ISSUE TITLE
Вот такой файл не читается

### ISSUE THREAD

**Issue by adimetrius** [Vostok-space/odcey#2]
[Points.odc.zip](https://github.com/Vostok-space/odcey/files/10696825/Points.odc.zip)

А odcread читает его. Файл взят отсюда https://forum.oberoncore.ru/viewtopic.php?f=134&t=6891&p=116964#p116964, его соседи так же не читаются.

**Comment by ComdivByZero** [comment]
Не получается воспроизвести. 

1. Не работает отдельной командой или в связке с git? 
2. Откуда взят odcey?

**Comment by ComdivByZero** [comment]
Не получается воспроизвести.

Не работает отдельной командой или в связке с git?
Откуда взят odcey?

**Comment by adimetrius** [comment]
antonio@hpbb:/tmp/0/Mod$ odcey text Figures.odc 
Can not open input

То же самое при ./Figures.odc

Установил на днях
/usr/bin/sudo snap install odcey

**Comment by adimetrius** [comment]
При этом другие odc тем же установленным odcey читаются благополучно

**Comment by ComdivByZero** [comment]
Это особенность snap. Он не даёт доступа к общему /tmp, и каждый snap-пакет использует собственный tmp. При обращении к таким файлам лучше использовать стандартный ввод

    odcey text < /tmp/0/Mod/Figures.odc

**Comment by adimetrius** [comment]
omg, неожиданные особенности snap... жизнь стала еще сложнее...

тогда в midnight commander надо команду, как вы привели - чтоб универсально было. испробовал - работает
